### ISSUE TITLE
What does `m2emulator_fixes.txt` do?

### ISSUE THREAD

**Issue by biggestsonicfan** [SailorSat/daytona-utils#4]
Greetings,

I have applied the patch from the document, but I can not observe any difference in gameplay. It's also not documented within the text file of what this code explicitly fixes.

Further, your commit 05bc485b13883f2dfbccdfa121270b69a11f0e3f references "m2em 1.1b", and I am unsure if that means the patch was applied to a Model2 Emulator v 1.1b, or if you are designating the patch as 1.1b.

**Comment by SailorSat** [comment]
long story short. the hack changes the code of the network thread is executing when "select"ing a socket.
in net-state 0/1 (link up phase) there is an instant timeout of 0, which is changed to 16ms.

background: newer games (2b/2c) usually "enable" the comm board, then write there config to it.

m2em code waits 60 reads before "firing up" - however, with no timeout set, those 60 reads are instant.
on real hardware the comm board takes some time to wake up.

hence m2em never reads the actual config, but all zeros.

and yes. "1.1b" refers to the patched 1.1a

**Comment by biggestsonicfan** [comment]
Mystery solved! Thank you!
